export const formQuestions: Record<string, any[]> = {
  de: [
    {
      field: 'employerName',
      question: 'Wie heißt dein Arbeitgeber? (Vollständiger Firmenname)',
      type: 'text',
      validation: 'required',
      examples: ['Beispiel GmbH', 'Muster AG', 'Test & Co. KG'],
      help: 'Den vollständigen Namen findest du auf deinem Arbeitsvertrag'
    },
    {
      field: 'employerNumber',
      question: 'Wie lautet die Betriebsnummer deines Arbeitgebers?',
      type: 'text',
      validation: 'required|digits:8',
      examples: ['12345678', '87654321'],
      help: 'Die 8-stellige Nummer findest du auf Lohnabrechnungen oder beim Arbeitgeber erfragen'
    },
    {
      field: 'employerAddress',
      question: 'Wie lautet die Adresse deines Arbeitgebers? (Straße, Hausnummer, PLZ, Ort)',
      type: 'text',
      validation: 'required',
      examples: ['Musterstraße 123, 12345 Berlin', 'Beispielweg 45, 80331 München'],
    },
    {
      field: 'employeeFirstName',
      question: 'Wie ist dein Vorname?',
      type: 'text',
      validation: 'required',
      examples: ['Max', 'Maria', 'Ahmed'],
    },
    {
      field: 'employeeLastName',
      question: 'Wie ist dein Nachname?',
      type: 'text',
      validation: 'required',
      examples: ['Mustermann', 'Schmidt', 'Kowalski'],
    },
    {
      field: 'employeeBirthDate',
      question: 'Wann wurdest du geboren? (TT.MM.JJJJ)',
      type: 'date',
      validation: 'required|date',
      examples: ['15.03.1990', '01.01.1985', '23.07.1995'],
    },
    {
      field: 'employeeNationality',
      question: 'Welche Staatsangehörigkeit hast du?',
      type: 'text',
      validation: 'required',
      examples: ['Ukrainisch', 'Türkisch', 'Syrisch', 'Polnisch'],
    },
    {
      field: 'employeePassport',
      question: 'Wie lautet deine Passnummer?',
      type: 'text',
      validation: 'required',
      examples: ['C01X00T47', 'AA1234567'],
    },
    {
      field: 'employmentStartDate',
      question: 'Wann beginnt dein Arbeitsverhältnis? (TT.MM.JJJJ)',
      type: 'date',
      validation: 'required|date',
      examples: ['01.01.2024', '15.02.2024', '01.03.2024'],
    },
    {
      field: 'employmentEndDate',
      question: 'Ist das Arbeitsverhältnis befristet? Wenn ja, bis wann? (TT.MM.JJJJ oder "unbefristet")',
      type: 'text',
      validation: 'required',
      examples: ['31.12.2024', 'unbefristet', '30.06.2025'],
    },
    {
      field: 'jobTitle',
      question: 'Was ist deine Berufsbezeichnung?',
      type: 'text',
      validation: 'required',
      examples: ['Softwareentwickler', 'Krankenpfleger', 'Elektriker', 'Verkäufer'],
    },
    {
      field: 'jobDescription',
      question: 'Beschreibe kurz deine Haupttätigkeiten (2-3 Sätze)',
      type: 'text',
      validation: 'required',
      examples: ['Entwicklung von Webanwendungen und Wartung bestehender Systeme'],
    },
    {
      field: 'weeklyHours',
      question: 'Wie viele Stunden arbeitest du pro Woche?',
      type: 'number',
      validation: 'required|numeric|min:1|max:48',
      examples: ['40', '35', '20', '30'],
    },
    {
      field: 'monthlySalary',
      question: 'Wie hoch ist dein monatliches Bruttogehalt in Euro?',
      type: 'number',
      validation: 'required|numeric|min:520',
      examples: ['2500', '3000', '1800', '4000'],
    },
  ],
  en: [
    {
      field: 'employerName',
      question: 'What is your employer\'s name? (Full company name)',
      type: 'text',
      validation: 'required',
      examples: ['Example GmbH', 'Sample AG', 'Test & Co. KG'],
      help: 'You can find the full name on your employment contract'
    },
    {
      field: 'employerNumber',
      question: 'What is your employer\'s company number?',
      type: 'text',
      validation: 'required|digits:8',
      examples: ['12345678', '87654321'],
      help: 'The 8-digit number can be found on pay slips or ask your employer'
    },
    {
      field: 'employerAddress',
      question: 'What is your employer\'s address? (Street, Number, Postal Code, City)',
      type: 'text',
      validation: 'required',
      examples: ['Sample Street 123, 12345 Berlin', 'Example Way 45, 80331 Munich'],
    },
    {
      field: 'employeeFirstName',
      question: 'What is your first name?',
      type: 'text',
      validation: 'required',
      examples: ['John', 'Maria', 'Ahmed'],
    },
    {
      field: 'employeeLastName',
      question: 'What is your last name?',
      type: 'text',
      validation: 'required',
      examples: ['Smith', 'Johnson', 'Williams'],
    },
    {
      field: 'employeeBirthDate',
      question: 'When were you born? (DD.MM.YYYY)',
      type: 'date',
      validation: 'required|date',
      examples: ['15.03.1990', '01.01.1985', '23.07.1995'],
    },
    {
      field: 'employeeNationality',
      question: 'What is your nationality?',
      type: 'text',
      validation: 'required',
      examples: ['Ukrainian', 'Turkish', 'Syrian', 'Polish'],
    },
    {
      field: 'employeePassport',
      question: 'What is your passport number?',
      type: 'text',
      validation: 'required',
      examples: ['C01X00T47', 'AA1234567'],
    },
    {
      field: 'employmentStartDate',
      question: 'When does your employment start? (DD.MM.YYYY)',
      type: 'date',
      validation: 'required|date',
      examples: ['01.01.2024', '15.02.2024', '01.03.2024'],
    },
    {
      field: 'employmentEndDate',
      question: 'Is the employment temporary? If yes, until when? (DD.MM.YYYY or "permanent")',
      type: 'text',
      validation: 'required',
      examples: ['31.12.2024', 'permanent', '30.06.2025'],
    },
    {
      field: 'jobTitle',
      question: 'What is your job title?',
      type: 'text',
      validation: 'required',
      examples: ['Software Developer', 'Nurse', 'Electrician', 'Sales Assistant'],
    },
    {
      field: 'jobDescription',
      question: 'Briefly describe your main activities (2-3 sentences)',
      type: 'text',
      validation: 'required',
      examples: ['Developing web applications and maintaining existing systems'],
    },
    {
      field: 'weeklyHours',
      question: 'How many hours do you work per week?',
      type: 'number',
      validation: 'required|numeric|min:1|max:48',
      examples: ['40', '35', '20', '30'],
    },
    {
      field: 'monthlySalary',
      question: 'What is your monthly gross salary in euros?',
      type: 'number',
      validation: 'required|numeric|min:520',
      examples: ['2500', '3000', '1800', '4000'],
    },
  ],
  uk: [
    {
      field: 'employerName',
      question: 'Як називається ваш роботодавець? (Повна назва компанії)',
      type: 'text',
      validation: 'required',
      examples: ['Приклад GmbH', 'Зразок AG', 'Тест & Co. KG'],
      help: 'Повну назву можна знайти у вашому трудовому договорі'
    },
    // ... similar translations for Ukrainian
  ],
};